### ISSUE TITLE
Support regexes when removing znodes

### ISSUE THREAD

**Issue by mkwhitacre** [davidledwards/zookeeper#15]
I have a use case where I'd like to be able to remove nodes in a path that match a specific regex.  Essentially I'd to do something like the following:

```
zk> rm -r -f fakeTest*
```

And have it remove all of the nodes in the current path that matched the path regex.

**Comment by davidledwards** [comment]
Good idea. This may also be useful in other commands. What about introducing a `find` command with a limited set of operations that could be applied?

For example, to recursively find and remove all nodes whose name begins with `foo` starting at the path `/bar`:
```
find -r foo.* /bar --rm
```
The implication with `--rm` is that `--force` would be implied because it seems impractical to add a conditional version check. I could be wrong here, but that is my intuition.

General syntax of `find` would be:
```
usage: find [OPTIONS] PATTERN [PATH] [COMMAND]
```

`PATTERN` is a regular expression, either very basic syntax or strictly according to the [JDK](http://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html). `PATH` is an optional starting path, which defaults to `pwd`. `COMMAND` would be a limited set of commands that make sense to apply, where something like `--print` is the default.

**Comment by mkwhitacre** [comment]
Additional features like find would definitely be good.  I'd also suggest having a "verbose" option or inversely "quiet" on the find command such that a consumer can more easily find out what the find command is actually doing (which nodes did it match on such that it is removing them?).

**Comment by davidledwards** [comment]
Finished adding support for `find` command. You can get help with `zk --help find`. There are also several examples in the README.

Note that this version only supports strict regular expressions as defined by Java 1.6, which means patterns you might expect to work like `foo*` must be expressed as `foo.*`. I might add simple pattern matching if this becomes too much of a burden for users.

https://github.com/davidledwards/zookeeper/tree/release-1.3
