### ISSUE TITLE
Could `cd` to a non-exist node

### ISSUE THREAD

**Issue by gengmao** [davidledwards/zookeeper#19]
```
zk> cd zookeeper/quota/fake
zk> pwd
/zookeeper/quota/fake
zk> ls
/zookeeper/quota/fake: no such node
```

**Comment by davidledwards** [comment]
This behavior is actually intentional. It essentially boiled down to a tradeoff.

Because the `zk` client is stateful in the context of `cd`, it maintains the perception of location in the path hierarchy. It does not necessarily reflect reality, though, since ZooKeeper may have an entirely different view of the actual path hierarchy.

This can be illustrated with another example. Suppose `cd` did, in fact, verify the presence of the node path. Now, consider the actions of two separate actors in the following order.

Actor 1
```
zk> cd zookeeper/quota/fake
<path must exist>
```

Actor 2
```
zk> rm zookeeper/quota/fake
<fake is removed>
```

Actor 1
```
zk> ls
/zookeeper/quota/fake: no such node
```

I chose to keep the UI and implementation simple since these sorts of edge cases lead to precisely the same outcome.

You can also issue `cd -c ...`, which performs a call to check the existence of the node, though does not fail the command. But, again, the state of the path could change.

**Comment by gengmao** [comment]
Hi @davidledwards, thanks for prompt reply. 

I just did a few more shell tests on my mac: 
Actor 1 - can't cd to a non-existing folder 
```
mao-mac:~ mao$ cd fake
-bash: cd: fake: No such file or directory
```
Actor 1 - create the folder and cd into
```
mao-mac:~ mao$ mkdir fake
mao-mac:~ mao$ cd fake
mao-mac:fake mao$ pwd
/Users/mao/fake
```
Actor 2 - remove the current folder of Actor 1
```
mao-mac:fake mao$ rm -rf /Users/mao/fake
<fake is removed>
```
Actor 1 - no error when ls current folder though
```
mao-mac:fake mao$ ls
```
Actor 1 - error when ls the absolute path, or create child folder
```
mao-mac:fake mao$ ls /Users/mao/fake
ls: /Users/mao/fake: No such file or directory
mao-mac:fake mao$ mkdir child1
mkdir: .: No such file or directory
```

Btw, I think this issue is minor. Just noticed the behavior is slightly different from unix shells, so that I wanted to point it out. It is totally fine if you think it is too trivial to keep such compliances - which won't hurts this tool's value. Please feel free to close. 

I found this tool is very handy for a zookeeper task on my hand. Better than the default zkCli.sh one. Thanks for sharing it.

**Comment by davidledwards** [comment]
I am open to making changes if it helps reduce any friction. I can certainly perform the equivalent of a `cd --check ...` and fail the command should the node not exist. However, absent some clever trickery, the same sort of condition would manifest itself if another actor were to remove that node. But, I suppose most people would be willing to accept that condition in exchange for greater certainty about the validity of the path. Let me solicit opinion from others that are using the `zk` tool before deciding on a change.

**Comment by mkwhitacre** [comment]
For my usage of the tool I'm not sure the proactive checking will necessarily add a lot of value since the moment you try to do an action on a non-existent node the user gets feedback about the state of the node.  If a user could do something like the following successfully:

```
zk> cd /some/fake/path
zk> mk child
```
And the tool would actually create nodes for the path /some/fake/path/child then that seems like the side effects would be surprising or prone to unintended changes.  Since the tool currently fails with the "mk" b/c the parents don't exist then I get the feedback I want regardless of if it is proactively checked.  

We don't currently have any tools that rely on the current behavior to remain passive so if a change was made that would be ok too.

**Comment by davidledwards** [comment]
Correct observation. All commands would fail if the underlying node is not present. However, if you were to use `mk -r child`, then all intervening nodes would be created as a side effect.

At this point, I am a bit reluctant to make a behavioral change, so will close the issue.

By the way, I typically use the TAB key to autocomplete sub-nodes, which obviously must query ZooKeeper for the candidate list. In a sense, TAB is sort of functioning like a safe version of `cd` since it's only presenting to the user what it knows to be sub-nodes. Of course, the state of those sub-nodes could change at any time, thus leaving the user in precisely the same scenario.
