### ISSUE TITLE
implement getSessionId

### ISSUE THREAD

**Issue by KannarFr** [davidledwards/zookeeper#29]
There is a way or should we implement zk.getSessionId?

**Comment by davidledwards** [comment]
That could be easily defined/implemented on the Zookeeper trait. I assume this is what you're asking?

**Comment by KannarFr** [comment]
Yup

**Comment by davidledwards** [comment]
Since the session id is already an attribute on the `Credential` trait, I decided to solve this problem by exposing `Session` on the base `Zookeeper` trait. This provides more information, if needed, including the session state.

So, to get the session id...
```scala
zk.session.credential.id
```

The intermediate types are guaranteed to be non-`null` regardless of the state of the connection.

**Comment by davidledwards** [comment]
https://github.com/davidledwards/zookeeper/tree/release-1.6

**Comment by KannarFr** [comment]
Nice thanks a lot.
